Repository Libra-foundation/react-template, pull requests merged in 2023-01, with the labels that each got.

#18 Force ESLint directives to be comment
  .eslintrc.json
  package-lock.json
  package.json
  src/Scripts/reportWebVitals.ts
Labels: enhancement

#20 [BUG] Fixing various ESLint related bugs
  .eslintrc.json
  package-lock.json
  package.json
  src/Scripts/reportWebVitals.ts
Labels: bug

#30 [BUG]Hot fixes
  .eslintrc.json
  tsconfig.json
Labels: bug, enhancement

#43 [BUG] Re fixed #36
  .eslintrc.json
Labels: bug

#49 [FEATURE] Migration from CRA to vite
  .env.development
  .env.preproduction
  .env.production
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  EnvFiles/.env.development
  EnvFiles/.env.preproduction
  EnvFiles/.env.production
  JestConfig/svgTransform.js
  babel.config.js
  index.html
  jest.config.ts
  package-lock.json
  package.json
  src/App.test.tsx
  src/Components/DummyComponent/DummyComponent.tsx
  src/EnvConfig.ts
  src/Scripts/reportWebVitals.ts
  src/index.tsx
  src/react-app-env.d.ts
  src/setupTests.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#53 [REFACTOR]: Migration delete useless dependencies
  package-lock.json
  package.json
Labels: Refactor

#54 [FEATURE] : React Template 2.0
  .env.development
  .env.preproduction
  .env.production
  .eslintrc.json
  .github/workflows/coverage.yml
  .prettierignore
  .prettierrc.json
  EnvFiles/.env.development
  EnvFiles/.env.preproduction
  EnvFiles/.env.production
  JestConfig/svgTransform.js
  babel.config.js
  index.html
  jest.config.ts
  package-lock.json
  package.json
  src/App.test.tsx
  src/Components/DummyComponent/DummyComponent.tsx
  src/EnvConfig.ts
  src/Scripts/reportWebVitals.ts
  src/index.tsx
  src/react-app-env.d.ts
  src/setupTests.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#62 [REFACTOR] : Changed jest config extension
  jest.config.js
Labels: Refactor

#61 [REFACTOR] : Merge PR pipelines
  .github/workflows/PR-checks.yml
  .github/workflows/build.yml
  .github/workflows/coverage.yml
  .github/workflows/lint.yml
Labels: Refactor

#63 [REFACTOR] : Added `has` boolean prefix eslint
  .eslintrc.json
Labels: Refactor

#66 [FEATURE] : Codeql workflow
  .github/workflows/codeql.yml
Labels: enhancement

#70 [REFACTOR] : Removed useless files
  index.html
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/Assets/logo.svg
Labels: Refactor
